accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.Signup.as_view(),name='signup')
]

groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path("posts/in/<slug>/",views.SingleGroup.as_view(),name="single"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.Createpost.as_view(),name='create'),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks')
]

accounts/models.py
from django.db import models
from django.contrib import auth
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):
    def __str__(self):
        return "@{}".format(self.username)

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()
from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,uniques=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        uniques_together = ('group','user')

posts/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
# Create your models here.

from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts',on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable = False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username','email','password1','password2')
        model = get_user_model()

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = 'Email Address'

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from . import forms
# Create your views here.
class Signup(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

groups/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth..mixins import (LoginRequiredMixin,
                                         PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your views here.

class PostList(SelectRelatedMixin,generic.ListView):
    model = model.Post
    selecte_related = ('user','group')

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post.user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = models.Post
    selecte_related = ('user','group')

    def get_queryset(Self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class Createpost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def  form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = modells.Post
    selecte_related=('user','group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get-queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

simplesocial/views.py
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Login In</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Login">
  </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
  <h1>Sign Up</h1>
  <form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-default" value="Sign Up">
  </form>
</div>
{% endblock %}

groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<h1>{{ group.name }}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="content">
  {% if user in group.members.all %}
    <a href="{% url 'groups:leave' slug.group.slug %}" class='btn btn-lg btn-full btn-warning'>
      <span class='glyphicon glyphicon-remove-circle'></span>Leave</a>
  {% else %}
  <a href="{% url 'groups:join' slug.group.slug %}" class='btn btn-lg btn-full btn-warning'>
    <span class='glyphicon glyphicon-ok-circle'></span>Join</a>

  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>No posts in this group yet!</h2>
  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" %}
  {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new group!</h4>
  <form action="{% url 'groups:create' %}" method="POST" id='groupForm'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submite" class='btn btn-primary btn-large' value="Create">
  </form>

{% endblock %}

groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
      <h2>Wlcome back!
        <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a>
      </h2>
    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the groups page!</p>
  </div>
  {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'>
      <span class='glyphicon glyphicon-plus-sign' >Create New Group!</span>
    </a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  <div class="list-group">
    {% for group in object_list %}
    <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
      <h3 class='title list-group-item-heading' >{{group.name}}</h3>
      <div class="list-group-item-text container-fluid">
        {{group.description_html|safe}}
        <div class="row">
          <div class="col-md-4">
            <span class='badge'>{{group.members.count}}</span>
            member{{group.members.count|pluralize}}
          </div>
          <div class="col-md-4">
            <span class='badge'>{{group.post.count}}</span>
            post{{group.posts.count|pluralize}}
          </div>
        </div>
      </div>
    </a>
    {% endfor %}
  </div>
</div>
{% endblock %}

posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost %} {% endblock %}
      {% block post_content %} {% endblock %}
      {% block post_post %} {% endblock %}
    </div>
  </div>
</div>


{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-light btn-large">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
<!-- </div> -->
{% endblock %}

posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<h4>Create a new Post</h4>
<form id='postForm' action="{% url 'posts:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class='btn btn-primary btn-large' value="post">
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends "post/posts_base.html" %}

{% block prep_post_content %}
<div class="col-md-4">
  {% if request.user.is_authenticated %}
  <div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">

				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as member_groups %} #}
				{% for member_group in get_user_groups %}
					<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
				{% endfor %}
			</ul>

		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
	<h1>@{{ post_user.username }}</h1>
	<p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
		{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Star Social</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="#" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="#"class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>

    <canvas id="canvas"></canvas>




    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Welcome to Star Social!</h1>
{% endblock %}  

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>thanks for visiting</h1>
{% endblock %}